spring.application.name=usermanagementsystemse
spring.datasource.url=jdbc:postgresql://localhost:5432/user_manage
spring.datasource.username=postgres
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
SECRET = "5367566859703373367639792F423F452848284D6251655468576D5A71347437"
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false